const core = require('@actions/core');
const github = require('@actions/github');

const WORKER_URL = 'https://api.difflog.io/validate-autopr';

async function run() {
  try {
    const openaiKey = core.getInput('openai_key', { required: true });
    const licenseKey = core.getInput('license_key') || '';
    const model = core.getInput('model') || 'gpt-4o-mini';
    const maxDiffLines = parseInt(core.getInput('max_diff_lines') || '500', 10);
    const skipIfBodySet = core.getInput('skip_if_body_set') !== 'false';
    const template = core.getInput('template') || '';

    const context = github.context;
    const { owner, repo } = context.repo;
    const pullNumber = context.payload.pull_request?.number;

    if (!pullNumber) {
      core.info('No pull request found in context. Skipping.');
      return;
    }

    const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

    // Get the PR
    const { data: pr } = await octokit.rest.pulls.get({ owner, repo, pull_number: pullNumber });

    // Skip if body already set
    if (skipIfBodySet && pr.body && pr.body.trim().length > 30) {
      core.info('PR already has a description. Skipping (skip_if_body_set=true).');
      return;
    }

    // Check if repo is private — if so, validate license
    const isPrivate = pr.head.repo?.private ?? false;
    if (isPrivate) {
      if (!licenseKey) {
        core.setFailed('AutoPR: private repo requires a license key. Get one at autopr.dev');
        return;
      }
      // Validate license
      try {
        const validateRes = await fetch(WORKER_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ license_key: licenseKey, repo: `${owner}/${repo}` })
        });
        const validateData = await validateRes.json();
        if (!validateData.valid) {
          core.setFailed(`AutoPR: invalid license key. ${validateData.message || ''}`);
          return;
        }
      } catch (err) {
        core.warning(`AutoPR: license validation failed (${err.message}). Continuing anyway (fail-open).`);
      }
    }

    // Fetch the diff
    const { data: diff } = await octokit.rest.pulls.get({
      owner, repo, pull_number: pullNumber,
      mediaType: { format: 'diff' }
    });

    // Truncate diff
    const diffLines = String(diff).split('\n');
    let truncated = false;
    let diffText = diffLines.slice(0, maxDiffLines).join('\n');
    if (diffLines.length > maxDiffLines) {
      truncated = true;
      diffText += `\n\n[Diff truncated at ${maxDiffLines} lines — this is a large PR. Consider splitting.]`;
    }

    // Load template if provided
    let templateContent = '';
    if (template) {
      try {
        const fs = require('fs');
        templateContent = fs.readFileSync(template, 'utf8');
      } catch (e) {
        core.warning(`AutoPR: could not read template file ${template}: ${e.message}`);
      }
    }

    // Build prompt
    const systemPrompt = `You are a senior software engineer writing pull request descriptions. Given a git diff, write a clear, concise PR description.

Format your response as markdown with these sections:
## Summary
2-3 sentences describing what changed and why.

## Changes
Bullet list grouped by type. Use these headers only if relevant:
- **Breaking changes:**
- **New features:**
- **Bug fixes:**
- **Refactors:**
- **Chores:**

## Testing notes
What reviewers should verify. Infer from test file changes and diff context.

## Affected areas
Which modules, directories, or components were touched.

${templateContent ? `\nUse this PR template as a guide for structure:\n${templateContent}` : ''}

Keep it factual. Don't be verbose. Reviewers are busy.`;

    const userPrompt = `PR title: ${pr.title}\n\nDiff:\n${diffText}`;

    // Call OpenAI
    const openaiRes = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openaiKey}`
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 1000,
        temperature: 0.3
      })
    });

    if (!openaiRes.ok) {
      const err = await openaiRes.text();
      core.setFailed(`AutoPR: OpenAI API error: ${err}`);
      return;
    }

    const openaiData = await openaiRes.json();
    let body = openaiData.choices?.[0]?.message?.content || '';

    if (!body) {
      core.setFailed('AutoPR: OpenAI returned empty response.');
      return;
    }

    // Append footer
    body += '\n\n---\n*Generated by [AutoPR](https://autopr.dev)*';

    // Write PR description
    await octokit.rest.pulls.update({
      owner, repo, pull_number: pullNumber, body
    });

    core.info(`AutoPR: PR #${pullNumber} description updated successfully.`);

  } catch (err) {
    core.setFailed(`AutoPR failed: ${err.message}`);
  }
}

run();
